Repository kubevirt/community, pull requests merged in 2019-11, with the labels that each got.

#36 Update README.md
  events/2019-kubecon-na/README.md
Labels: approved, dco-signoff: no, lgtm, size/XS

#37 Add KubeCon meetup location
  events/2019-kubecon-na/README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#38 Update Owners
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#39 Add room details to kubecon meetup
  events/2019-kubecon-na/README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS
