Repository kubevirt/community, pull requests merged in 2019-07, with the labels that each got.

#25 Feat: Added documentation section, created CI/CD and Offtopic inside
  docs/CI-CD/how-to-prow.md
  docs/CI-CD/prow-jobs.md
  docs/README.md
  docs/off-topic/how-to-bazel.md
Labels: approved, kind/enhancement, lgtm, size/L

#23 Dark color logo variants
  logo/KubeVirt_logo_black.png
  logo/KubeVirt_logo_black.svg
  logo/KubeVirt_logo_color.png
  logo/KubeVirt_logo_color.svg
Labels: approved, lgtm, size/L

#26 Sync owners with kubevirt.github.io
  OWNERS
Labels: approved, kind/enhancement, lgtm, size/XS

#29 Remove non logo file
  .gitignore
  logo/.DS_Store
Labels: approved, kind/bug, lgtm, size/XS

#30 Add Pedro to owners
  OWNERS
Labels: approved, lgtm, size/XS

#31 Move relocations to emeritus
  OWNERS
Labels: approved, lgtm, size/S

#32 Addind the CentOS ci-cd howto get an account
  docs/CI-CD/centos-ci-cd.md
  docs/README.md
Labels: approved, lgtm, size/M
