Repository kubevirt/community, pull requests merged in 2020-11, with the labels that each got.

#43 Document workflow
  docs/article-workflow.md
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, lifecycle/stale, size/L

#47 Remove reference to trello
  README.md
Labels: dco-signoff: yes, size/XS

#48 Update OWNERS
  OWNERS
Labels: dco-signoff: yes, size/S
