Repository kubevirt/community, pull requests merged in 2021-09, with the labels that each got.

#123 Approver-led governance for Kubevirt
  GOVERNANCE.md
  MAINTAINERS.md
Labels: size/L, lgtm, approved, dco-signoff: yes, ok-to-test

#129 Add Ryan Hallisey as maintainer
  MAINTAINERS.md
Labels: size/XS, lgtm, approved, dco-signoff: yes

#111 Initial commit for CNCF incubating due diligence
  proposals/governance/incubation_dd.md
Labels: enhancement, size/L, lgtm, approved, dco-signoff: yes

#128 Update MAINTAINERS.md
  MAINTAINERS.md
Labels: size/XS, lgtm, approved, dco-signoff: yes

#133 Updates per upstream CNCF/ToC peer review
  proposals/governance/incubation_dd.md
Labels: size/M, lgtm, approved, dco-signoff: yes

#132 proposal for HCO implementation of the golden image feature
  design-proposals/golden-image-delivery-and-update-pipeline.md
Labels: size/M, lgtm, approved, dco-signoff: yes
