Repository kubevirt/community, pull requests merged in 2021-04, with the labels that each got.

#76 Initial commit for new membership policy page
  membership_checklist.md
  membership_policy.md
Labels: dco-signoff: yes, lgtm, size/L

#89 Create contributing.md
  contributors/contributing.md
Labels: dco-signoff: yes, lgtm, size/XS

#86 Initial commit to create member_dd directory and simple README.md
  member_dd/README.md
Labels: dco-signoff: yes, size/XS

#93 Update CI/CD docs.
  docs/CI-CD/centos-ci-cd.md
  docs/CI-CD/how-to-prow.md
  docs/CI-CD/prow-jobs.md
  docs/README.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#91 Design proposal process documentation
  design-proposals/README.md
  design-proposals/proposal-template.md
Labels: dco-signoff: yes, lgtm, size/L

#85 Initial commit for community meeting page
  responsibilities/community_meeting.md
Labels: dco-signoff: yes, lgtm, size/M

#100 Add sigs validator
  go.mod
  go.sum
  sigs.yaml
  validators/cmd/sigs/README.md
  validators/cmd/sigs/sigs-validator.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#106 Presentation proposal for All Things Open - 2021
  conference-proposals/2021-all-things-open/README.md
Labels: approved, dco-signoff: yes, lgtm, size/S
