Repository kubevirt/community, pull requests merged in 2021-01, with the labels that each got.

#50 Add sigs.yaml and script for generation
  hack/generate-devstats-repo-sql.py
  sigs.yaml
Labels: dco-signoff: yes, lgtm, size/L

#55 proposal for vm snapshot session
  events/2021-kubevirt-summit/proposals/snapshot-dev.md
  events/2021-kubevirt-summit/proposals/vm-snapshots.md
Labels: dco-signoff: yes, lgtm, size/M

#59 Batch VM API 2021 summit proposal
  events/2021-kubevirt-summit/proposals/vm-batch-api.md
Labels: dco-signoff: yes, lgtm, size/S

#69 KubeVirt Summit 2021 Presentation Proposal: KubeVirt Updates
  events/2021-kubevirt-summit/proposals/kubevirt-updates.md
Labels: dco-signoff: yes, size/M

#65 Propose privilege dropping presentation for KubevirtCon2021
  events/2021-kubevirt-summit/proposals/privilege-dropping.md
Labels: dco-signoff: yes, lgtm, size/M

#62 KubeVirt summit session proposal: "How to avoid merging broken code with automated testing using prow"
  events/2021-kubevirt-summit/proposals/prow-jobs-automated-testing.md
Labels: dco-signoff: yes, size/M

#58 proposal for kubevirt hotplug session
  events/2021-kubevirt-summit/proposals/proposal-awels.md
Labels: dco-signoff: yes, lgtm, size/S

#66 KubevirtCon2021 proposal: Automated migration of Virtual Machines from VMware or OpenStack to KubeVirt
  events/2021-kubevirt-summit/proposals/migrating-vms-to-kubevirt-with-coriolis.md
Labels: dco-signoff: yes, lgtm, needs-ok-to-test, size/M

#68 add CPU pinning proposal
  events/2021-kubevirt-summit/proposals/cpu-pinning.md
Labels: dco-signoff: yes, lgtm, needs-ok-to-test, size/S

#72 KubeVirt Summit 2021 proposal: Harvester with KubeVirt
  events/2021-kubevirt-summit/proposals/harvester.md
Labels: dco-signoff: yes, lgtm, needs-ok-to-test, size/M

#71 KubeVirt Summit 2021 session proposal: PCI passthrough
  events/2021-kubevirt-summit/proposals/pci-passthrough.md
Labels: dco-signoff: yes, lgtm, size/S

#74 Summit 2021: User Story: Moving a VFX Studio to the Cloud with Kubernetes and Kubevirt
  events/2021-kubevirt-summit/proposals/user-story-vfx-production.md
Labels: dco-signoff: yes, needs-ok-to-test, size/S

#61 Proposal: Moving oVirt and VMware VMs to KubeVirt with VM Import Operator and Forklift
  events/2021-kubevirt-summit/proposals/kubevirt-vmio.md
Labels: dco-signoff: yes, lgtm, size/M

#70 Proposal: Automating KubeVirt with Tekton Pipelines
  events/2021-kubevirt-summit/automating-kubevirt-with-tekton-pipelines.md
Labels: dco-signoff: yes, lgtm, size/S

#60 Propose molecule-kubevirt presentation
  events/2021-kubevirt-summit/proposals/molecule-kubevirt.md
Labels: dco-signoff: yes, lgtm, needs-ok-to-test, size/M

#77 move proposal Automating KubeVirt with Tekton Pipelines to the right directory
  events/2021-kubevirt-summit/proposals/automating-kubevirt-with-tekton-pipelines.md
Labels: approved, dco-signoff: yes, lgtm, size/XS
