Repository kubevirt/community, pull requests merged in 2021-02, with the labels that each got.

#63 Proposal: common-templates
  events/2021-kubevirt-summit/proposals/common-templates.md
Labels: dco-signoff: yes, size/M

#57 KubeVirt opinionated deployment via Hyperconverged Cluster Operator
  events/2021-kubevirt-summit/proposals/hco-user-proposal-2021.md
Labels: dco-signoff: yes, size/M

#73 Propose session about SRIOV Live Migration
  events/2021-kubevirt-summit/proposals/sriov-live-migration.md
Labels: dco-signoff: yes, size/S

#79 change presentes for the HCO talk
  events/2021-kubevirt-summit/proposals/hco-user-proposal-2021.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#78 Add information about the KubeVirt v1 session
  events/2021-kubevirt-summit/proposals/the-road-to-v1.md
Labels: dco-signoff: yes, lgtm, size/M
