Repository kubevirt/community, pull requests merged in 2022-03, with the labels that each got.

#167 Adding David and Vladik as approvers
  OWNERS
Labels: size/XS, lgtm, approved, dco-signoff: yes

#159 VM Cloning design proposal
  design-proposals/VM-cloning.md
Labels: size/L, lgtm, approved, dco-signoff: yes

#162 Virtual Machine "raw" volume export proposal
  design-proposals/export-import/volume-export.md
Labels: size/L, lgtm, approved, dco-signoff: yes

#168 Garbage Collect Completed DVs - Design Proposal
  design-proposals/garbage-collect-completed-dvs.md
Labels: size/M, lgtm, approved, dco-signoff: yes
