Repository kubevirt/community, pull requests merged in 2022-04, with the labels that each got.

#169 maintainers: Welcome Andrew
  MAINTAINERS.md
Labels: size/XS, lgtm, approved, dco-signoff: yes

#164 VM memory dump design proposal
  design-proposals/vm-memory-dump.md
Labels: size/L, lgtm, approved, dco-signoff: yes

#171 Correcting the github ID for Andrew Burden
  MAINTAINERS.md
Labels: size/XS, lgtm, approved, dco-signoff: yes, needs-ok-to-test

#172 Update membership-policy to specify valid OWNERS files in sponsor requirements
  membership_policy.md
Labels: size/XS, lgtm, approved, dco-signoff: yes
