Repository kubevirt/community, pull requests merged in 2023-02, with the labels that each got.

#204 Adding event page for Google Summer of Code 2023 submission
  events/2023-summerofcode/README.md
Labels: size/M, lgtm, approved, dco-signoff: yes

#207 Adding github issue inks to GSoC 23 page
  events/2023-summerofcode/README.md
Labels: size/XS, lgtm, approved, dco-signoff: yes

#208 Fix: formatting and grammar
  design-proposals/README.md
Labels: size/XS, lgtm, approved, dco-signoff: yes, needs-ok-to-test
