Repository kubevirt/community, pull requests merged in 2023-12, with the labels that each got.

#225 Proposal: mass machine type transition
  design-proposals/mass_machine_type_transition.md
Labels: size/L, lgtm, dco-signoff: yes

#250 community, owners: add aburdenthehand as approver
  OWNERS
Labels: size/XS, lgtm, approved, dco-signoff: yes

#242 Proposal for VM rollout strategy
  design-proposals/vm-rollout-strategy/vm-rollout-strategy.md
Labels: size/L, lgtm, approved, dco-signoff: yes
