Repository kubevirt/community, pull requests merged in 2024-09, with the labels that each got.

#312 community: generate sig-list.md
  Makefile
  generators/cmd/sigs/README.md
  generators/cmd/sigs/main.go
  generators/cmd/sigs/sig-list.gomd
  go.mod
  go.sum
  pkg/sigs/sigs.go
  pkg/sigs/types.go
  sig-list.md
  sigs.yaml
  validators/cmd/sigs/sigs-validator.go
Labels: size/L, lgtm, approved, dco-signoff: yes

#319 owners: adding myself as an approver
  OWNERS
Labels: size/XS, lgtm, approved, dco-signoff: yes

#301 community, wg, template: create wg templates
  GOVERNANCE.md
  README.md
  wg-TEMPLATE/README.md
  wg-TEMPLATE/wg-charter-template.md
Labels: size/L, lgtm, approved, dco-signoff: yes, needs-approver-review

#306 membership, policy: add SIG, WG and subproject roles
  membership_policy.md
Labels: size/M, lgtm, approved, dco-signoff: yes, needs-approver-review

#328 community,OWNERS: self nomination of dhiller as reviewer
  OWNERS
Labels: size/XS, lgtm, approved, dco-signoff: yes
