Repository kubevirt/community, pull requests merged in 2024-05, with the labels that each got.

#251 design-proposal: Feature lifecycle
  design-proposals/feature-lifecycle.md
Labels: size/L, lgtm, approved, dco-signoff: yes

#246 virt-handler: Restrict write access to nodes
  design-proposals/shadow-node.md
Labels: size/L, lgtm, approved, dco-signoff: yes

#273 kubevirt, sig-ci: add charter and entry in sigs.yaml
  sig-ci/charter.md
  sigs.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#292 sig-ci: correct meeting time zone
  sigs.yaml
Labels: size/XS, lgtm, approved, dco-signoff: yes
