Repository kubevirt/community, pull requests merged in 2024-04, with the labels that each got.

#260 design proposal: volume update strategy
  design-proposals/volume-update-strategy.md
Labels: size/L, lgtm, approved, dco-signoff: yes

#282 Add sig-observability charter
  sig-observability/charter.md
Labels: size/M, lgtm, approved, dco-signoff: yes

#271 sig-network charter
  sig-network/charter.md
Labels: size/M, lgtm, approved, dco-signoff: yes

#284 Add sig-observability to sigs.yaml
  sigs.yaml
Labels: size/S, lgtm, approved, dco-signoff: yes

#274 sig-storage: extend charter with sig responsabilities
  sig-storage/charter.md
Labels: size/M, lgtm, approved, dco-signoff: yes

#264 Proposal: KubeVirtBMC
  design-proposals/kubevirtbmc.md
Labels: size/L, lgtm, approved, dco-signoff: yes

#281 network binding plugin: DownwardAPI for device info
  design-proposals/network-binding-plugin/network-binding-plugin.md
Labels: size/L, sig/network, lgtm, approved, dco-signoff: yes, sig/api

#279 ipam: integrate w/ k8s multi-network defacto standard persistent IPs
  design-proposals/sdn-ipam-secondary-nets.md
Labels: size/XL, sig/network, lgtm, approved, dco-signoff: yes

#272 kubevirt, sig-buildsystem: add charter and entry in sigs.yaml
  sig-TEMPLATE/sig-charter-template-prefilled.md
  sig-TEMPLATE/sig-charter-template.md
  sig-buildsystem/charter.md
  sigs.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#276 Introduce a sig-compute charter
  sig-compute/charter.md
  sigs.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes
