Repository kubevirt/community, pull requests merged in 2024-11, with the labels that each got.

#341 sigs, labels: add observability label
  sig-list.md
  sigs.yaml
Labels: size/XS, lgtm, approved, dco-signoff: yes

#298 community, wg, arch: add wg, sig subprojects and charter for S390x and ARM
  sigs.yaml
  wg-arch-arm/charter.md
  wg-arch-s390x/charter.md
Labels: size/L, lgtm, approved, dco-signoff: yes

#349 sigs.yaml: fix indentation of ci-s390x subproject
  sigs.yaml
Labels: size/S, lgtm, approved, dco-signoff: yes, kind/cleanup

#348 community,labels,sig-list: update/remove labels
  sig-list.md
  sigs.yaml
Labels: size/S, lgtm, approved, dco-signoff: yes, kind/cleanup

#346 sigs,generate: update sig-list generation for wgs
  generators/cmd/sigs/sig-list.gomd
  pkg/sigs/types.go
  sig-list.md
Labels: size/M, lgtm, approved, dco-signoff: yes

#326 design-proposal: instancetype.kubevirt.io - Expand during submission
  design-proposals/instancetype.kubevirt.io/expand-during-submission.md
Labels: size/L, lgtm, approved, dco-signoff: yes, sig/compute

#333 community,wg,code-quality: establish working group code-quality
  sig-list.md
  sigs.yaml
  wg-code-quality/wg-charter.md
Labels: size/M, lgtm, approved, dco-signoff: yes

#354 sigs: Nominate Edward Haas (eddev) as the sig-network chair
  sig-list.md
  sigs.yaml
Labels: size/XS, lgtm, approved, dco-signoff: yes

#353 Add sig-observability deatils
  sig-list.md
  sigs.yaml
Labels: size/S, lgtm, approved, dco-signoff: yes

#355 sigs: Update the sig-network subprojects
  sigs.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes

#323 design-proposal: instancetype.kubevirt.io - pkg/instancetype refactor
  design-proposals/instancetype.kubevirt.io/pkg-instancetype-refactor.md
Labels: size/L, lgtm, approved, dco-signoff: yes, sig/compute

#329 Removing Alona, cwilkers, & jobbler from reviewer/approver
  OWNERS
Labels: size/XS, lgtm, approved, dco-signoff: yes, needs-approver-review

#357 Fix and extend the Dynamic Primary Pod NIC Name proposal to support rename
  design-proposals/dynamic-primary-pod-nic-name.md
Labels: size/L, lgtm, approved, dco-signoff: yes

#358 sigs: Nominate Miguel Duarte Barroso as sig-network chair
  sig-list.md
  sigs.yaml
Labels: size/XS, lgtm, approved, dco-signoff: yes

#350 sigs,generate: improve validation, update sig-list generation
  Makefile
  generators/cmd/sigs/sig-list.gomd
  pkg/labels/file.go
  pkg/labels/types.go
  pkg/orgs/file.go
  pkg/orgs/types.go
  pkg/orgs/types_test.go
  pkg/sigs/file.go
  pkg/sigs/types.go
  sig-list.md
  sigs.yaml
  validators/cmd/sigs/sigs-validator.go
Labels: size/XXL, lgtm, approved, dco-signoff: yes
