Repository kubevirt/community, pull requests merged in 2024-12, with the labels that each got.

#344 Updating orgs.yaml link in membership_policy.md
  membership_policy.md
Labels: size/XS, lgtm, approved, dco-signoff: yes, needs-approver-review

#367 Adding note to MAINTAINERS that Vasiliy is on temp leave
  MAINTAINERS.md
Labels: size/XS, lgtm, approved, dco-signoff: yes

#313 design-proposal: Adjust virtiofs feature gates
  design-proposals/virtiofs-support/virtiofs-feature-gates.md
Labels: size/M, sig/storage, lgtm, approved, dco-signoff: yes, sig/compute, needs-approver-review

#364 community,membership policy: update devstats link
  membership_policy.md
Labels: size/XS, lgtm, approved, dco-signoff: yes

#361 cli-tool: generate github contribution reports using the Github GraphQL api
  generators/cmd/contributions/README.md
  generators/cmd/contributions/default-config.yaml
  generators/cmd/contributions/main.go
  generators/cmd/contributions/report.go
  go.mod
  go.sum
  pkg/contributions/types.go
  pkg/contributions/user-contribution.go
  pkg/owners/file.go
  pkg/owners/types.go
Labels: size/XXL, lgtm, approved, dco-signoff: yes

#322 design-proposal: rewrite node-labeller to be more modular and testable
  design-proposals/node-labeller-refactor.md
Labels: size/M, lgtm, approved, dco-signoff: yes, sig/compute

#362 New process for handling virtualization proposals
  design-proposals/new-proposals-framework.md
Labels: size/M, lgtm, approved, dco-signoff: yes
