Repository kubevirt/community, pull requests merged in 2024-03, with the labels that each got.

#263 governance, kubevirt, org: add inactive member section
  membership_policy.md
Labels: size/M, lgtm, approved, dco-signoff: yes

#266 kubevirt, chore: add ALUMNI.md
  ALUMNI.md
Labels: size/L, lgtm, approved, dco-signoff: yes

#267 CNCF: Rename some files to make their destiny more clear
  CNCF/README.md
  CNCF/incubation/due-diligence.md
Labels: size/XS, lgtm, approved, dco-signoff: yes

#261 SIGs: Remove some SIGs
  hack/generate-devstats-repo-sql.py
  sigs.yaml
Labels: size/S, lgtm, approved, dco-signoff: yes

#265 Add SIG template
  GOVERNANCE.md
  community_meeting.md
  sig-TEMPLATE/README.md
  sig-TEMPLATE/sig-charter-template-prefilled.md
  sig-TEMPLATE/sig-charter-template.md
  sig-scale/charter.md
  sig-storage/charter.md
Labels: size/L, lgtm, approved, dco-signoff: yes

#269 community: add help-wanted.md
  contributors/help-wanted.md
Labels: size/L, lgtm, approved, dco-signoff: yes

#258 Design proposal: Descheduler support
  design-proposals/descheduler-support.md
Labels: size/M, lgtm, approved, dco-signoff: yes

#278 Adding more content to community README to help guide folks
  README.md
Labels: size/S, lgtm, approved, dco-signoff: yes

#280 design-proposal: Network binding plugin
  design-proposals/network-binding-plugin/integtation-points.png
  design-proposals/network-binding-plugin/network-binding-plugin.md
Labels: size/XL, lgtm, approved, dco-signoff: yes
