Repository kubevirt/community, pull requests merged in 2024-06, with the labels that each got.

#295 Drop feature gate in descheduler support design proposal
  design-proposals/descheduler-support.md
Labels: size/S, lgtm, approved, dco-signoff: yes

#268 design-proposal: Introduce LiveUpdate support for instance types
  design-proposals/instancetype-vm-rollout-support.md
Labels: size/L, lgtm, approved, dco-signoff: yes

#287 instancetype: Extend `PreferSpread`
  design-proposals/instancetype.kubevirt.io/default-instancetypes-from-volumes.md
  design-proposals/instancetype.kubevirt.io/extend-preferSpread.md
  design-proposals/instancetype.kubevirt.io/flavors-and-preferences.md
Labels: size/L, lgtm, approved, dco-signoff: yes

#277 Update sig-scale charter
  sig-scale/charter.md
  sigs.yaml
Labels: size/M, lgtm, approved, dco-signoff: yes
