Repository kubevirt/community, pull requests merged in 2025-01, with the labels that each got.

#351 community,alumni: replace md with generator
  ALUMNI.md
  Makefile
  alumni.yaml
  generators/cmd/alumni/ALUMNI.gomd
  generators/cmd/alumni/README.md
  generators/cmd/alumni/main.go
Labels: size/XL, lgtm, approved, dco-signoff: yes, needs-approver-review

#375 Update feature-lifecycle.md to make the purpose of a subsection clearer
  design-proposals/feature-lifecycle.md
Labels: size/XS, lgtm, approved, dco-signoff: yes

#373 chore(sigs.yaml): Add missing dir to sig-compute-instancetype
  sigs.yaml
Labels: size/XS, lgtm, approved, dco-signoff: yes

#360 OWNERS: enable SIGs, WGs and automation code writers to own their folders
  OWNERS
  OWNERS_ALIASES
  generators/OWNERS
  hack/OWNERS
  pkg/OWNERS
  sig-TEMPLATE/OWNERS
  sig-buildsystem/OWNERS
  sig-ci/OWNERS
  sig-compute/OWNERS
  sig-network/OWNERS
  sig-observability/OWNERS
  sig-scale/OWNERS
  sig-storage/OWNERS
  validators/OWNERS
  wg-TEMPLATE/OWNERS
  wg-arch-arm/OWNERS
  wg-arch-s390x/OWNERS
  wg-code-quality/OWNERS
Labels: size/L, lgtm, approved, dco-signoff: yes, needs-approver-review

#374 sigs.yaml: Add sig-compute-virtctl subproject
  sigs.yaml
Labels: size/S, lgtm, approved, dco-signoff: yes

#377 design-proposal: limit Live Migration initial permissions to cluster-admin
  design-proposals/hardening-vmim.md
Labels: size/L, lgtm, approved, dco-signoff: yes

#379 New Security Section
  design-proposals/proposal-template.md
Labels: size/XS, lgtm, approved, dco-signoff: yes

#366 Adding maintainer responsibilities, off-boarding, and emeritus governance docs
  GOVERNANCE.md
  MAINTAINERS.md
  membership_policy.md
Labels: size/M, lgtm, approved, dco-signoff: yes, needs-approver-review

#380 General technical review of the KubeVirt project
  CNCF/general_technical_review.md
Labels: size/L, lgtm, approved, dco-signoff: yes
