Repository kubevirt/community, pull requests merged in 2025-04, with the labels that each got.

#401 sigs.yaml: add sig-compute meetings
  sig-list.md
  sigs.yaml
Labels: size/S, lgtm, approved, dco-signoff: yes

#403 fix(spelling): sig-compute charter.md
  sig-compute/charter.md
Labels: size/XS, lgtm, approved, dco-signoff: yes

#224 Add Helm charts proposal
  design-proposals/helm-chart.md
Labels: size/L, lgtm, approved, dco-signoff: yes, needs-ok-to-test
